version: "3.6"
services:
  game-api:
    build:
      context: ./
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/game
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: game
      POSTGRES_PASSWORD: game
      POSTGRES_DB: game
    ports:
      - "5432:5432"