INSERT INTO game (name, publication_date)
VALUES ('Assassin''s Creed', '2022-11-15'),
       ('The Witcher 3: Wild Hunt', '2015-05-19'),
       ('Minecraft', '2011-11-18'),
       ('Fortnite', '2017-07-25'),
       ('Call of Duty: Warzone', '2020-03-10'),
       ('FIFA 22', '2021-10-01'),
       ('Red Dead Redemption 2', '2018-10-26'),
       ('Cyberpunk 2077', '2020-12-10'),
       ('Among Us', '2018-06-15'),
       ('Overwatch', '2016-05-24'),
       ('Animal Crossing: New Horizons', '2020-03-20'),
       ('Doom Eternal', '2020-03-20'),
       ('Mortal Kombat 11', '2019-04-23'),
       ('Spider-Man: Miles Morales', '2020-11-12'),
       ('League of Legends', '2009-10-27'),
       ('World of Warcraft', '2004-11-23'),
       ('StarCraft II', '2010-07-27'),
       ('Genshin Impact', '2020-09-28'),
       ('Hades', '2020-09-17'),
       ('Among Us', '2018-06-15'),
       ('Apex Legends', '2019-02-04'),
       ('Valorant', '2020-06-02'),
       ('The Elder Scrolls V: Skyrim', '2011-11-11'),
       ('Rocket League', '2015-07-07'),
       ('Terraria', '2011-05-16'),
       ('Civilization VI', '2016-10-21');

INSERT INTO editor (name)
VALUES ('Ubisoft'),
       ('CD Projekt'),
       ('Mojang'),
       ('Epic Games'),
       ('Activision'),
       ('EA Sports'),
       ('Rockstar Games'),
       ('CD Projekt Red'),
       ('Innersloth'),
       ('Blizzard Entertainment'),
       ('Nintendo EPD'),
       ('id Software'),
       ('NetherRealm Studios'),
       ('Insomniac Games'),
       ('Riot Games'),
       ('Blizzard Entertainment'),
       ('Riot Games'),
       ('miHoYo'),
       ('Supergiant Games'),
       ('Innersloth'),
       ('Respawn Entertainment'),
       ('Square Enix'),
       ('Bethesda Softworks'),
       ('Psyonix'),
       ('Re-Logic');


INSERT INTO studio (name)
VALUES ('Ubisoft Montreal'),
       ('CD Projekt Red'),
       ('Mojang Studios'),
       ('Epic Games'),
       ('Infinity Ward'),
       ('EA Vancouver'),
       ('Rockstar North'),
       ('CD Projekt Red'),
       ('Innersloth'),
       ('Blizzard Entertainment'),
       ('Nintendo EPD'),
       ('id Software'),
       ('NetherRealm Studios'),
       ('Insomniac Games'),
       ('Riot Games'),
       ('Blizzard Entertainment'),
       ('Riot Games'),
       ('miHoYo'),
       ('Supergiant Games'),
       ('Innersloth'),
       ('Respawn Entertainment'),
       ('Square Enix'),
       ('Bethesda Game Studios'),
       ('Psyonix'),
       ('Re-Logic');


INSERT INTO game_editor (game_id, editor_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (14, 14),
       (15, 15),
       (16, 16),
       (17, 17),
       (18, 18),
       (19, 19),
       (20, 20),
       (21, 9),
       (22, 21),
       (23, 22),
       (24, 23),
       (25, 24);

INSERT INTO game_studio (game_id, studio_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (14, 14),
       (15, 15),
       (16, 16),
       (17, 17),
       (18, 18),
       (19, 19),
       (20, 20),
       (21, 9),
       (22, 21),
       (23, 22),
       (24, 23),
       (25, 24);

INSERT INTO game_genre (game_id, genre)
VALUES (1, 'Action'),
       (1, 'Adventure'),
       (1, 'Stealth'),
       (2, 'Action'),
       (2, 'Role-playing'),
       (2, 'Open-world'),
       (3, 'Sandbox'),
       (3, 'Survival'),
       (3, 'Indie'),
       (4, 'Battle Royale'),
       (4, 'Shooter'),
       (4, 'Survival'),
       (5, 'First-person Shooter'),
       (5, 'Battle Royale'),
       (5, 'Action'),
       (6, 'Sports'),
       (6, 'Football'),
       (6, 'Simulation'),
       (7, 'Action-adventure'),
       (7, 'Western'),
       (7, 'Open-world'),
       (8, 'Action RPG'),
       (8, 'Open-world'),
       (8, 'Cyberpunk'),
       (9, 'Party'),
       (9, 'Social Deduction'),
       (9, 'Indie'),
       (10, 'First-person Shooter'),
       (10, 'Multiplayer'),
       (10, 'Team-based'),
       (11, 'Life Simulation'),
       (11, 'Social'),
       (11, 'Farming'),
       (12, 'First-person Shooter'),
       (12, 'Action'),
       (12, 'Demonic'),
       (13, 'Fighting'),
       (13, 'Competitive'),
       (13, 'Violent'),
       (14, 'Action-adventure'),
       (14, 'Superhero'),
       (14, 'Open-world'),
       (15, 'MOBA'),
       (15, 'Team-based'),
       (15, 'Strategy'),
       (16, 'MMORPG'),
       (16, 'Fantasy'),
       (16, 'PvP'),
       (17, 'Real-time Strategy'),
       (17, 'Sci-Fi'),
       (17, 'Tactical'),
       (18, 'Action RPG'),
       (18, 'Fantasy'),
       (18, 'Magic'),
       (19, 'Action RPG'),
       (19, 'Adventure'),
       (19, 'Open-world'),
       (20, 'Action-adventure'),
       (20, 'Roguelike'),
       (20, 'Isometric'),
       (21, 'Party'),
       (21, 'Social Deduction'),
       (21, 'Indie'),
       (22, 'Battle Royale'),
       (22, 'FPS'),
       (22, 'Hero-based'),
       (23, 'Open-world RPG'),
       (23, 'Fantasy'),
       (23, 'Adventure'),
       (24, 'Sports'),
       (24, 'Racing'),
       (24, 'Football'),
       (25, 'Action-adventure'),
       (25, 'Survival Horror'),
       (25, 'Zombies');


INSERT INTO game_platform (game_id, platform)
VALUES (1, 'PC'),
       (1, 'PlayStation 4'),
       (1, 'Xbox One'),
       (2, 'PlayStation 4'),
       (2, 'Xbox One'),
       (2, 'Nintendo Switch'),
       (3, 'PC'),
       (3, 'PlayStation 4'),
       (3, 'Xbox One'),
       (4, 'PC'),
       (4, 'PlayStation 4'),
       (4, 'Xbox One'),
       (5, 'PC'),
       (5, 'PlayStation 4'),
       (5, 'Xbox One'),
       (6, 'PC'),
       (6, 'PlayStation 4'),
       (6, 'Xbox One'),
       (7, 'PlayStation 4'),
       (7, 'Xbox One'),
       (7, 'PC'),
       (8, 'PC'),
       (8, 'PlayStation 4'),
       (8, 'Xbox One'),
       (9, 'Mobile'),
       (9, 'PC'),
       (9, 'Nintendo Switch'),
       (10, 'PC'),
       (10, 'PlayStation 4'),
       (10, 'Xbox One'),
       (11, 'PC'),
       (11, 'PlayStation 4'),
       (11, 'Xbox One'),
       (12, 'PC'),
       (12, 'PlayStation 4'),
       (12, 'Xbox One'),
       (13, 'PlayStation 4'),
       (13, 'Xbox One'),
       (13, 'PC'),
       (14, 'PlayStation 5'),
       (14, 'PlayStation 4'),
       (14, 'PC'),
       (15, 'PlayStation 4'),
       (15, 'PlayStation 5'),
       (15, 'PC'),
       (16, 'PC'),
       (16, 'Mac'),
       (16, 'Linux'),
       (17, 'PC'),
       (17, 'Mac'),
       (17, 'Linux'),
       (18, 'PC'),
       (18, 'Mac'),
       (18, 'Linux'),
       (19, 'PC'),
       (19, 'PlayStation 4'),
       (19, 'Xbox One'),
       (20, 'PC'),
       (20, 'PlayStation 4'),
       (20, 'Xbox One'),
       (21, 'Mobile'),
       (21, 'PC'),
       (21, 'Nintendo Switch'),
       (22, 'PC'),
       (22, 'PlayStation 4'),
       (22, 'Xbox One'),
       (23, 'PC'),
       (23, 'PlayStation 4'),
       (23, 'Xbox One'),
       (24, 'PC'),
       (24, 'PlayStation 4'),
       (24, 'Xbox One'),
       (25, 'PC'),
       (25, 'PlayStation 4'),
       (25, 'Xbox One');
